# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'baseProgram' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for baseProgram
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
#  pod 'MBProgressHUD+MJ'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SVProgressHUD'
  pod 'Masonry'
end
